version: '3.1'
services:
  innosig_iqoption_predict_scheduler:
    container_name: innosig_iqoption_predict_scheduler
    image: innosig_iqoption_predict_scheduler
    build:
      context: .
      dockerfile: Docker/scheduler/Dockerfile
    volumes:
      - ./src:/app
    restart: always
    networks:
      - external-network

  # Flask server
  innosig_iqoption_predict_api:
    container_name: innosig_iqoption_predict_api
    build:
      context: .
      dockerfile: Docker/api/Dockerfile
    image: innosig_iqoption_predict_api
    volumes:
      - ./src:/app
    environment:
      - PORT=7777
    restart: always
    networks:
      - external-network

networks:
  external-network:
    external:
      name: innosig-backend-backtesting_internal-network