version: '3.1'
services:
  # Socket server
#  innopred_socket:
#    container_name: innopred_socket
#    build:
#      context: .
#      dockerfile: Docker/socket/Dockerfile
#    image: innopred_socket
#    volumes:
#      - ./src:/app
#    ports:
#      - 5000:5000
#    restart: always
#    networks:
#      - internal_network

  innopred_redis:
    image: redis
    container_name: innopred_redis
    restart: always
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - internal_network
    volumes:
      - ./data/redis_data:/data

#Docker Networks
networks:
  internal_network:
    driver: bridge